#include<stdio.h>
int main()
{
    int n,i=2,j=0,k=0,ntemp;
    scanf("%d",&n);
    ntemp=n;
    while(n!=1)
    {
        printf("%d\n",i);
        if(n%i==0)
        {
            n=n/i;
            j++;
            if(j==3)
            {
                break;
            }
        }
        if(n%i==1&&k==0)
        {
            j=1;
            i++;
        }
        if(n%i==1)
        {
            j=1;
            i++;
        }
        k++;
    }
    if(j!=3)
    {
        if(ntemp==1)
        {
            ntemp=1;
        }
        printf("%d",ntemp);
    }
    if(j>=3)
        printf("Not Cube Free");
}
